// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CapsuleOpenEffectController from "./capsule_open_effect_controller.js"
application.register("capsule-open-effect", CapsuleOpenEffectController)

import EditFormController from "./edit_form_controller.js"
application.register("edit-form", EditFormController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
